version: '3.8'

services:
  fastapi:
    image: satzweb/fastapi:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  streamlit:
    image: satzweb/streamlit:latest
    build:
      context: ./streamlit_app
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://fastapi:8000


